name: Caliper test
version: "2.0.0"

caliper:
  blockchain: fabric

channels:
  - channelName: evoting-channel
    contracts:
    - id: evoting-chaincode

organizations:
  - mspid: Org1MSP
    identities:
      certificates:
      - name: 'Inf-User1'
        clientPrivateKey:
          path: '../test-network/organizations/peerOrganizations/org1.example.com/users/Inf-User1@org1.example.com/msp/keystore/17536f086a5a39ef2e2b59ff3cd0786453c00a0aa12e8480a2ddd94cbbf19c90_sk'
        clientSignedCert:
          path: '../test-network/organizations/peerOrganizations/org1.example.com/users/Inf-User1@org1.example.com/msp/signcerts/cert.pem'
    connectionProfile:
      path: '../test-network/organizations/peerOrganizations/org1.example.com/connection-org1.yaml'
      discover: true
